import {
  Home,
  Book,
  GraduationCap,
  Video,
  User,
  Settings,
  Users,
  CreditCard,
  Search,
  X,
  Calendar,
  Clock,
  PlayCircle,
  BookOpen,
  UserCircle,
  Menu,
  ArrowLeft,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Mail,
  Lock,
  Phone,
  MapPin,
  Star,
  Heart,
  Share,
  Download,
  Upload,
  RefreshCw,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Shield,
  Wifi,
  WifiOff,
  Signal,
  Battery,
  Volume2,
  VolumeX,
  Camera,
  Image,
  FileText,
  Folder,
  Save,
  Copy,
  Undo,
  Redo,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RotateCw,
  Maximize,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  Filter,
  Grid,
  List,
  Globe,
  Link,
  ExternalLink,
  Bookmark,
  Tag,
  Flag,
  Award,
  Trophy,
  Target,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  Activity,
  Zap,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Umbrella,
  Thermometer,
  Wind,
  Compass,
  Navigation,
  Map,
  Layers,
  Package,
  ShoppingCart,
  ShoppingBag,
  DollarSign,
  Percent,
  Calculator,
  PlusCircle,
  MinusCircle,
  XCircle,
  CheckCircle,
  AlertTriangle,
  AlertOctagon,
  MessageCircle,
  MessageSquare,
  Send,
  Inbox,
  Archive,
  Trash,
  Delete,
  Edit3,
  Edit2,
  PenTool,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Hash,
  AtSign,
  Paperclip,
  Mic,
  MicOff,
  Headphones,
  Speaker,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,
  Volume,
  Volume1,
  Radio,
  Tv,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  HardDrive,
  Server,
  Database,
  Cpu,
  MemoryStick,
  Usb,
  Bluetooth,
  Rss,
  QrCode,
  Scan,
  Printer,
  FileImage,
  FileVideo,
  FileAudio,
  FilePlus,
  FileMinus,
  FileX,
  FileCheck,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  Package2,
  Briefcase,
  Building,
  Building2,
  Store,
  Factory,
  Warehouse,
  Truck,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Fuel,
  Navigation2,
  Anchor,
  Sailboat,
  Waves,
  Mountain,
  TreePine,
  Flower,
  Leaf,
  Sprout,
  Apple,
  Cherry,
  Grape,
  Banana,
  Coffee,
  Wine,
  Beer,
  Martini,
  Pizza,
  Sandwich,
  Cookie,
  Cake,
  IceCream,
  Candy,
  Gift,
  PartyPopper,
  Crown,
  Gem,
  Diamond,
  Key,
  Unlock,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Fingerprint,
  UserCheck,
  UserX,
  UserPlus,
  UserMinus,
  UserCircle2,
  Contact,
  Baby,
  PersonStanding,
  Accessibility,
  Stethoscope,
  Pill,
  Syringe,
  Badge,
  HeartPulse,
  Brain,
  Bone,
  Glasses,
  Shirt,
  Footprints,
  Watch,
  Palette,
  Brush,
  Paintbrush,
  Scissors,
  Ruler,
  Triangle,
  Circle,
  Pentagon,
  Hexagon,
  Octagon,
  Spade,
  Club,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Gamepad,
  Gamepad2,
  Joystick,
  Puzzle,
  Crosshair,
  Focus,
  Aperture,
  Film,
  Clapperboard,
  Images,
  Crop,
  Move,
  MousePointer,
  MousePointer2,
  Hand,
  Barcode,
  Binary,
  Code,
  Code2,
  CodeSquare,
  Terminal,
  Command,
  Option,
  Space,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftUp,
  CornerLeftDown,
  CornerRightUp,
  CornerRightDown,
  Move3d,
  FlipHorizontal,
  FlipVertical,
  Maximize2,
  Minimize2,
  Expand,
  Shrink,
  SearchCheck,
  SearchX,
  FilterX,
  SortAsc,
  SortDesc,
  ArrowUpDown,
  ArrowLeftRight,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowUpLeft,
  Repeat1,
  RefreshCcw,
  Fullscreen,
  PictureInPicture,
  PictureInPicture2,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  PanelTopClose,
  PanelTopOpen,
  PanelBottomClose,
  PanelBottomOpen,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Columns,
  Rows,
  Grid3x3,
  Grid2x2,
  Table,
  Table2,
  Minus,
  Divide,
  Equal,
  Infinity,
  Pi,
  Sigma,
} from 'lucide-react-native';

// Icon mapping from Material Icons to Lucide React Native
export const iconMap: Record<string, any> = {
  // Navigation & UI
  'home': Home,
  'book': Book,
  'school': GraduationCap,
  'videocam': Video,
  'person': User,
  'account-circle': UserCircle,
  'settings': Settings,
  'dashboard': Settings, // Using Settings as Dashboard doesn't exist
  'people': Users,
  'payment': CreditCard,
  'admin-panel-settings': Shield,
  
  // Actions
  'search': Search,
  'close': X,
  'schedule': Calendar,
  'access-time': Clock,
  'play-circle': PlayCircle,
  'menu-book': BookOpen,
  'menu': Menu,
  'arrow-back': ArrowLeft,
  'add': Plus,
  'edit': Edit,
  'delete': Trash2,
  'visibility': Eye,
  'visibility-off': EyeOff,
  'eye': Eye,
  'eye-off': EyeOff,
  'refresh': RefreshCw,
  'check': Check,
  'error': AlertCircle,
  'info': Info,
  'help': HelpCircle,
  
  // Communication
  'email': Mail,
  'lock': Lock,
  'phone': Phone,
  'location-on': MapPin,
  
  // Media & Content
  'star': Star,
  'favorite': Heart,
  'share': Share,
  'download': Download,
  'upload': Upload,
  'camera': Camera,
  'image': Image,
  'folder': Folder,
  'save': Save,
  
  // Navigation arrows
  'keyboard-arrow-left': ChevronLeft,
  'keyboard-arrow-right': ChevronRight,
  'keyboard-arrow-up': ChevronUp,
  'keyboard-arrow-down': ChevronDown,
  'arrow-upward': ArrowUp,
  'arrow-downward': ArrowDown,
  'arrow-forward': ArrowRight,
  
  // More actions
  'more-horiz': MoreHorizontal,
  'more-vert': MoreVertical,
  'filter-list': Filter,
  'sort': ArrowUpDown, // Using ArrowUpDown as Sort doesn't exist
  'view-module': Grid,
  'view-list': List,
  
  // Status & Feedback
  'check-circle': CheckCircle,
  'cancel': XCircle,
  'warning': AlertTriangle,
  'error-outline': AlertCircle,
  'info-outline': Info,
  
  // Communication & Social
  'message': MessageCircle,
  'send': Send,
  'inbox': Inbox,
  'archive': Archive,
  
  // File & Document
  'description': FileText,
  'folder-open': Folder,
  'insert-drive-file': FileText,
  'picture-as-pdf': FileText,
  
  // Media Controls
  'play-arrow': Play,
  'pause': Pause,
  'stop': Square,
  'skip-previous': SkipBack,
  'skip-next': SkipForward,
  'fast-rewind': Rewind,
  'fast-forward': FastForward,
  'repeat': Repeat,
  'shuffle': Shuffle,
  'volume-up': Volume2,
  'volume-off': VolumeX,
  
  // Device & Hardware
  'wifi': Wifi,
  'signal-wifi-off': WifiOff,
  'signal-cellular-4-bar': Signal,
  'battery-full': Battery,
  'bluetooth': Bluetooth,
  'print': Printer,
  
  // Shopping & Commerce
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'attach-money': DollarSign,
  
  // Math & Science
  'calculate': Calculator,
  'functions': Calculator, // Using Calculator as Function doesn't exist
  'percent': Percent,
  'add-circle': PlusCircle,
  'remove-circle': MinusCircle,
  'plus': Plus,
  
  // Time & Calendar
  'today': Calendar,
  'event': Calendar,
  'alarm': Clock,
  'timer': Clock,
  'watch-later': Clock,
  
  // Location & Maps
  'place': MapPin,
  'my-location': Navigation,
  'explore': Compass,
  'map': Map,
  'directions': Navigation2,
  
  // Security & Privacy
  'security': Shield,
  'lock-outline': Lock,
  'lock-open': Unlock,
  'verified-user': ShieldCheck,
  'fingerprint': Fingerprint,
  
  // User & Profile
  'person-add': UserPlus,
  'person-remove': UserMinus,
  'group': Users,
  'supervisor-account': Users,
  'account-box': UserCircle,
  
  // Content & Media
  'photo': Image,
  'photo-library': Images,
  'video-library': Video,
  'music-note': Volume2,
  'headset': Headphones,
  
  // Tools & Utilities
  'build': Settings,
  'tune': Settings,
  'color-lens': Palette,
  'brush': Brush,
  'content-cut': Scissors,
  'straighten': Ruler,
  
  // Shapes & Symbols
  'radio-button-unchecked': Circle,
  'check-box-outline-blank': Square,
  'star-border': Star,
  'favorite-border': Heart,
  
  // Text & Formatting
  'format-bold': Bold,
  'format-italic': Italic,
  'format-underlined': Underline,
  'format-align-left': AlignLeft,
  'format-align-center': AlignCenter,
  'format-align-right': AlignRight,
  'format-align-justify': AlignJustify,
  'format-list-bulleted': List,
  
  // Network & Connectivity
  'cloud': Cloud,
  'cloud-download': Download,
  'cloud-upload': Upload,
  'sync': RefreshCw,
  'offline-bolt': Zap,
  
  // Weather
  'wb-sunny': Sun,
  'brightness-2': Moon,
  'cloud-queue': Cloud,
  'grain': CloudRain,
  'beach-access': Umbrella,
  'thermostat': Thermometer,
  'air': Wind,
  
  // Transportation
  'directions-car': Car,
  'directions-bus': Bus,
  'train': Train,
  'flight': Plane,
  'directions-boat': Ship,
  'directions-bike': Bike,
  'two-wheeler': Bike, // Using Bike as Scooter doesn't exist
  'local-gas-station': Fuel,
  
  // Food & Dining
  'restaurant': Pizza,
  'local-cafe': Coffee,
  'wine-bar': Wine,
  'sports-bar': Beer,
  'local-pizza': Pizza,
  'cake': Cake,
  'icecream': IceCream,
  
  // Entertainment & Games
  'sports-esports': Gamepad,
  'casino': Dice1,
  'extension': Puzzle,
  'toys': Gift,
  'celebration': PartyPopper,
  
  // Health & Medical
  'local-hospital': HeartPulse,
  'healing': Badge,
  'medication': Pill,
  'psychology': Brain,
  'glasses': Glasses,
  
  // Fashion & Accessories
  'checkroom': Shirt,
  'watch': Watch,
  'diamond': Diamond,
  
  // Technology & Development
  'code': Code,
  'terminal': Terminal,
  'memory': Cpu,
  'storage': HardDrive,
  'router': Server,
  'developer-board': Database,
  'usb': Usb,
  
  // Business & Office
  'business': Building,
  'store': Store,
  'factory': Factory,
  'warehouse': Warehouse,
  'work': Briefcase,
  'assignment': FileText,
  'folder-shared': Folder,
  
  // Education & Learning
  'grade': Award,
  'emoji-events': Trophy,
  'military-tech': Target,
  
  // Charts & Analytics
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'analytics': Activity,
  'insights': BarChart,
  
  // Stats and Analytics icons
  'GraduationCap': GraduationCap,
  'BookOpen': BookOpen,
  'Video': Video,
  'Users': Users,
  
  // Default fallback
  'default': HelpCircle,
};

// Helper function to get Lucide icon component
export const getLucideIcon = (materialIconName: string) => {
  return iconMap[materialIconName] || iconMap['default'];
};