import { MD3LightTheme as DefaultTheme } from 'react-native-paper';
import { designSystem } from './designSystem';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    // Map design system colors to Material Design 3 colors
    primary: designSystem.colors.primary,
    primaryContainer: designSystem.colors.primaryLight + '20',
    secondary: designSystem.colors.secondary,
    secondaryContainer: designSystem.colors.secondaryLight + '20',
    tertiary: designSystem.colors.accent,
    tertiaryContainer: designSystem.colors.accentLight + '20',
    surface: designSystem.colors.surface,
    surfaceVariant: designSystem.colors.surfaceVariant,
    background: designSystem.colors.background,
    error: designSystem.colors.error,
    errorContainer: designSystem.colors.error + '20',
    onPrimary: designSystem.colors.textInverse,
    onSecondary: designSystem.colors.textInverse,
    onTertiary: designSystem.colors.textInverse,
    onSurface: designSystem.colors.textPrimary,
    onSurfaceVariant: designSystem.colors.textSecondary,
    onBackground: designSystem.colors.textPrimary,
    onError: designSystem.colors.textInverse,
    outline: designSystem.colors.border,
    outlineVariant: designSystem.colors.borderLight,
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: designSystem.colors.textPrimary,
    inverseOnSurface: designSystem.colors.textInverse,
    inversePrimary: designSystem.colors.primaryLight,
    elevation: {
      level0: 'transparent',
      level1: designSystem.colors.surface,
      level2: designSystem.colors.surface,
      level3: designSystem.colors.surface,
      level4: designSystem.colors.surface,
      level5: designSystem.colors.surface,
    },
    surfaceDisabled: designSystem.colors.surfaceVariant,
    onSurfaceDisabled: designSystem.colors.textTertiary,
    backdrop: 'rgba(0, 0, 0, 0.5)',
    // Custom colors from design system
    textPrimary: designSystem.colors.textPrimary,
    textSecondary: designSystem.colors.textSecondary,
    textTertiary: designSystem.colors.textTertiary,
    border: designSystem.colors.border,
    success: designSystem.colors.success,
    warning: designSystem.colors.warning,
    info: designSystem.colors.info,
    accent: designSystem.colors.accent,
    card: designSystem.colors.surface,
    cardHover: designSystem.colors.surfaceVariant,
    divider: designSystem.colors.border,
    overlay: 'rgba(0, 0, 0, 0.5)',
    // Status colors
    online: designSystem.colors.success,
    offline: designSystem.colors.textTertiary,
    away: designSystem.colors.warning,
    busy: designSystem.colors.error,
    // Course level colors
    foundation: designSystem.colors.foundation,
    intermediate: designSystem.colors.intermediate,
    advanced: designSystem.colors.advanced,
    expert: designSystem.colors.expert,
  },
  roundness: designSystem.borderRadius.lg,
  spacing: designSystem.spacing,
  shadows: designSystem.shadows,
};

export type Theme = typeof theme;
